### ISSUE TITLE
empty.js not found on test/data/fixtures.html

### ISSUE THREAD

**Issue by IsibisiDev** [jquery/sizzle#426]
The path of the empty.js file was not found on fixtures.html file. The two files are in the same folder, so the path would be `<script src="empty.js">`

**Comment by mgol** [comment]
Thanks for the report. This is caused by 131dc0c79cabe30243212818adc06778062a271c. @markelog could you explain why 404s are OK for local runs but not for Karma? And why only this file is problematic?

**Comment by IsibisiDev** [comment]
Of nothing, below list other errors in the various pages of the "test" folder.

**Page: test/index.html**
Errror(s): Failed to load sizzle/test/data/fixtures.html: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https. (Possible solution: https://stackoverflow.com/a/10752078)

**Page: test/data/midex_sort.html**
Error(s):
1) Uncaught TypeError: Cannot read property 'config' of undefined
    at testinit.js:4
    at testinit.js:17

2) Uncaught TypeError: Cannot read property 'compareDocumentPosition' of null
    at sortOrder (sizzle.js:885)
    at Array.sort (native)
    at Function.Sizzle.uniqueSort (sizzle.js:1057)
    at mixed_sort.html:16

**Page: test/data/noConflict.html**
Error(s): Uncaught TypeError: window.parent.iframeCallback is not a function
    at noConflict.html:30

**Comment by markelog** [comment]
Okay, so we need an empty file and reference in fixtures for this test - https://github.com/jquery/sizzle/blob/3116795bba9a0c3d624e0718006b25aa5568d4cb/test/unit/selector.js#L489

Such test checks selector with `script` tag with `src` attribute, so we need to put something in there. And since we referenced external stuff from it, browser should load it. But it does not matter what, we do not check that, we don't care.

> The two files are in the same folder, so the path would be <script src="empty.js">

Yes! Well... almost, should be `data/empty.js`, since we are loading [`fixture.html`](https://github.com/jquery/sizzle/blob/3116795bba9a0c3d624e0718006b25aa5568d4cb/test/data/testrunner.js#L22) and then [putting](https://github.com/jquery/sizzle/blob/3116795bba9a0c3d624e0718006b25aa5568d4cb/test/data/testrunner.js#L29) it in our qunit template.

So all paths from there will be relative to `index.html`... kinda thing.
But that's what we doing in the actual browser not in the karma (yep).

In the karma, we have to specify our own "base path" from which everything will be referenced - https://github.com/jquery/sizzle/blob/3116795bba9a0c3d624e0718006b25aa5568d4cb/test/karma/karma.conf.js#L22

(see a comment in there of why it should be like that).

In the browser it will be something like this -

<img width="1431" alt="screen shot 2018-08-29 at 22 00 08" src="https://user-images.githubusercontent.com/945528/44809928-d040e680-abd8-11e8-9fc7-e56c93fcefa0.png">

And only if you open the console, but when you run it in the karma environment without `base/test` prefix (here in phantom) -
```sh
λ ./node_modules/.bin/grunt karma:phantom
Running "karma:phantom" (karma) task
29 08 2018 21:47:36.682:WARN [watcher]: Pattern "/Users/markelog/Workspace/sizzle/empty.js" does not match any file.
29 08 2018 21:47:36.698:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
29 08 2018 21:47:36.698:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
29 08 2018 21:47:36.704:INFO [launcher]: Starting browser PhantomJS
29 08 2018 21:47:37.641:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket /#jFohI9VjimEJlHwaAAAA with id 99052703
29 08 2018 21:47:37.719:WARN [web-server]: 404: /empty.js?_=1535568457678
29 08 2018 21:47:37.764:WARN [web-server]: 404: /empty.js?_=1535568457679
29 08 2018 21:47:37.772:WARN [web-server]: 404: /empty.js?_=1535568457680
29 08 2018 21:47:37.782:WARN [web-server]: 404: /empty.js?_=1535568457681
29 08 2018 21:47:37.788:WARN [web-server]: 404: /empty.js?_=1535568457682
29 08 2018 21:47:37.794:WARN [web-server]: 404: /empty.js?_=1535568457683
29 08 2018 21:47:37.799:WARN [web-server]: 404: /empty.js?_=1535568457684
29 08 2018 21:47:37.805:WARN [web-server]: 404: /empty.js?_=1535568457685
29 08 2018 21:47:37.823:WARN [web-server]: 404: /empty.js?_=1535568457686
29 08 2018 21:47:37.829:WARN [web-server]: 404: /empty.js?_=1535568457687
29 08 2018 21:47:37.834:WARN [web-server]: 404: /empty.js?_=1535568457688
29 08 2018 21:47:37.840:WARN [web-server]: 404: /empty.js?_=1535568457689
29 08 2018 21:47:37.847:WARN [web-server]: 404: /empty.js?_=1535568457690
29 08 2018 21:47:37.852:WARN [web-server]: 404: /empty.js?_=1535568457691
29 08 2018 21:47:37.856:WARN [web-server]: 404: /empty.js?_=1535568457692
29 08 2018 21:47:37.860:WARN [web-server]: 404: /empty.js?_=1535568457693
29 08 2018 21:47:37.864:WARN [web-server]: 404: /empty.js?_=1535568457694
29 08 2018 21:47:37.870:WARN [web-server]: 404: /empty.js?_=1535568457695
29 08 2018 21:47:37.875:WARN [web-server]: 404: /empty.js?_=1535568457696
29 08 2018 21:47:37.880:WARN [web-server]: 404: /empty.js?_=1535568457697
29 08 2018 21:47:37.885:WARN [web-server]: 404: /empty.js?_=1535568457698
29 08 2018 21:47:37.895:WARN [web-server]: 404: /empty.js?_=1535568457699
29 08 2018 21:47:37.906:WARN [web-server]: 404: /empty.js?_=1535568457700
29 08 2018 21:47:37.913:WARN [web-server]: 404: /empty.js?_=1535568457701
29 08 2018 21:47:37.918:WARN [web-server]: 404: /empty.js?_=1535568457702
29 08 2018 21:47:37.924:WARN [web-server]: 404: /empty.js?_=1535568457703
29 08 2018 21:47:37.998:WARN [web-server]: 404: /empty.js?_=1535568457704
29 08 2018 21:47:38.016:WARN [web-server]: 404: /empty.js?_=1535568457705
29 08 2018 21:47:38.033:WARN [web-server]: 404: /empty.js?_=1535568457706
29 08 2018 21:47:38.048:WARN [web-server]: 404: /empty.js?_=1535568457707
29 08 2018 21:47:38.053:WARN [web-server]: 404: /empty.js?_=1535568457708
29 08 2018 21:47:38.057:WARN [web-server]: 404: /empty.js?_=1535568457709
29 08 2018 21:47:38.062:WARN [web-server]: 404: /empty.js?_=1535568457710
29 08 2018 21:47:38.067:WARN [web-server]: 404: /empty.js?_=1535568457711
29 08 2018 21:47:38.080:WARN [web-server]: 404: /empty.js?_=1535568457712
29 08 2018 21:47:38.089:WARN [web-server]: 404: /empty.js?_=1535568457713
29 08 2018 21:47:38.095:WARN [web-server]: 404: /empty.js?_=1535568457714
29 08 2018 21:47:38.109:WARN [web-server]: 404: /empty.js?_=1535568457715
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 37 of 54 SUCCESS (0 secs / 0.373 secs)
29 08 2018 21:47:38.183:WARN [web-server]: 404: /empty.js?_=1535568457716
29 08 2018 21:47:38.188:WARN [web-server]: 404: /empty.js?_=1535568457717
29 08 2018 21:47:38.194:WARN [web-server]: 404: /empty.js?_=1535568457718
29 08 2018 21:47:38.204:WARN [web-server]: 404: /empty.js?_=1535568457719
29 08 2018 21:47:38.210:WARN [web-server]: 404: /empty.js?_=1535568457720
29 08 2018 21:47:38.215:WARN [web-server]: 404: /empty.js?_=1535568457721
29 08 2018 21:47:38.220:WARN [web-server]: 404: /empty.js?_=1535568457722
29 08 2018 21:47:38.225:WARN [web-server]: 404: /empty.js?_=1535568457723
29 08 2018 21:47:38.229:WARN [web-server]: 404: /empty.js?_=1535568457724
29 08 2018 21:47:38.234:WARN [web-server]: 404: /empty.js?_=1535568457725
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 48 of 54 SUCCESS (0 secs / 0.5 secs)
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 49 of 54 SUCCESS (0 secs / 0.532 secs)
29 08 2018 21:47:38.308:WARN [web-server]: 404: /empty.js?_=1535568457728
29 08 2018 21:47:38.314:WARN [web-server]: 404: /empty.js?_=1535568457729
29 08 2018 21:47:38.319:WARN [web-server]: 404: /empty.js?_=1535568457730
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 54 of 54 SUCCESS (0.213 secs / 0.587 secs)
```

And since we are testing bazillion browsers in karma, multiple that ouput by the bazillion.

Cause of that discrepancy between root paths (or base paths :) in different environments we will get 404 errors, so we have to choose in which one. I chose to fix karma one.

Hackish, how I noticed in the commit, but it was almost five years ago! OMG I'm old now, where my life took me, damn :/.

Anyways, that's said, things might have changed/improve since then, so if you have something better in mind, would be cool to implement that :)

> below list other errors in the various pages of the "test" folder.

Yeah, you have to start a local server to make it right (I use https://github.com/indexzero/http-server). Back then, btw, you had to use LAMP stuff, was quirky and long to set up... those days! Haha

We probably should update the https://github.com/jquery/sizzle/tree/3116795bba9a0c3d624e0718006b25aa5568d4cb#testing bit, since it looks misleading

**Comment by IsibisiDev** [comment]
I'm on Windows 8.1. I had not considered inserting the sizzle folder on a web server (I currently own XAMPP).

**Comment by IsibisiDev** [comment]
There are updates: on the **test/index.html** page no more errors are found, but they remain on **test/data/midex_sort.html** and on **test/data/noConflict.html**. On **test/data/fixtures.html** I found this other mistake: _Failed to load resource: the server responded with a status of 404 (Not Found)_

**Comment by IsibisiDev** [comment]
I also found errors while testing the code and found these errors:
![image](https://user-images.githubusercontent.com/32841743/44949789-1eecbb80-ae39-11e8-8067-5d0753d1baab.png)
Source: at http://localhost/sizzle/test/unit/selector.js:372:7

--------------
![image](https://user-images.githubusercontent.com/32841743/44949806-62472a00-ae39-11e8-8140-02709994605a.png)

![image](https://user-images.githubusercontent.com/32841743/44949818-aafee300-ae39-11e8-85cf-e4a515d8f4ee.png)


--------------
![image](https://user-images.githubusercontent.com/32841743/44949810-7854ea80-ae39-11e8-9aea-ab3e60ce7673.png)

--------------

**Comment by markelog** [comment]
I don't see any failures at least in latest chrome and there is no failures in CI as well. 

So there is probably something wrong with your set up, although can't be 100%.
In any case, it seems your original concerns judging by the subject of this issue are now understood.

So I am closing the issue, if you have any other questions, it's better to ask them in the gitter channel - https://gitter.im/jquery/dev
